index/urls.py
from django.urls import path
from index.views import Landing, IndexPageView
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', IndexPageView.as_view(), name='index'),
    path('land_form.html', Landing.as_view(), name='land'),
    path('descricao.html', TemplateView.as_view(
        template_name='descricao.html'), name='descricao'),
    path('empresa.html', TemplateView.as_view(
        template_name='empresa.html'), name='empresa'),
    path('servicos.html', TemplateView.as_view(
        template_name='servicos.html'), name='servicos'),
    path('clientes.html', TemplateView.as_view(
        template_name='clientes.html'), name='clientes'),
    path('blog.html', TemplateView.as_view(
        template_name='blog.html'), name='blog'),
]

projclinicas/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from dashboard.api.viewsets import FuncionarioViewset
from processos.api.viewsets import AtivosViewset, PassivosViewset

router = DefaultRouter()
# router.register(r'bdclientes', ClientesViewset, base_name='ClientesViewset')
router.register(r'funcionario', FuncionarioViewset,
                base_name='FuncionarioViewset')
router.register(r'ativos', AtivosViewset, base_name='AtivosViewset')
router.register(r'passivos', PassivosViewset, base_name='PassivosViewset')

urlpatterns = [
    path('', include('index.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
    path('chatbot/', include('chatbot.urls')),
    path('', include(router.urls)),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/models.py
from django.db import models


class Land(models.Model):
    nome_empresa = models.CharField(max_length=50, blank=True, null=True)
    nome_contato = models.CharField(max_length=50, blank=True, null=True)
    celular = models.CharField(max_length=10, blank=True, null=True)
    email = models.EmailField(max_length=254, blank=True, null=True)
    CONSULTORIA = 'CS'
    TREINAMENTO = 'TR'
    MARKETING = 'MK'
    OUTROS = 'OU'

    INTERESSE = [
        (CONSULTORIA, 'Consultoria'),
        (TREINAMENTO, 'Treinamento'),
        (MARKETING, 'Marketing'),
        (OUTROS, 'Outros'),
    ]

    interesse = models.CharField(
        max_length=2,
        choices=INTERESSE,
        default=CONSULTORIA,
    )

models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Ativos(models.Model):
    id_ativo = models.CharField(primary_key=True, max_length=-1)
    tipo_ativo = models.CharField(max_length=20, blank=True, null=True)
    descricao_passivo = models.CharField(max_length=20, blank=True, null=True)
    valor_ativo = models.IntegerField(blank=True, null=True)
    data_ativo = models.DateField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'ativos'


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.BooleanField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.BooleanField()
    is_active = models.BooleanField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class DashboardAtivos(models.Model):
    id_ativo = models.SmallIntegerField(blank=True, null=True)
    nome = models.SmallIntegerField(blank=True, null=True)
    valor = models.SmallIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dashboard_ativos'


class DashboardClientes(models.Model):
    nome = models.CharField(max_length=30, blank=True, null=True)
    sobrenome = models.CharField(max_length=30, blank=True, null=True)
    cnpj = models.CharField(max_length=11, blank=True, null=True)
    celular = models.CharField(max_length=9, blank=True, null=True)
    email = models.CharField(max_length=254, blank=True, null=True)
    foto = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dashboard_clientes'


class DashboardClinica(models.Model):
    clinica_id = models.AutoField(primary_key=True)
    nomefantasia = models.CharField(max_length=100)
    cnpj = models.CharField(unique=True, max_length=100)
    email = models.CharField(max_length=20, blank=True, null=True)
    contato = models.CharField(max_length=11, blank=True, null=True)
    especialidade = models.CharField(max_length=30, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dashboard_clinica'


class DashboardContatos(models.Model):
    nome = models.CharField(max_length=50, blank=True, null=True)
    sobrenome = models.CharField(max_length=50, blank=True, null=True)
    telefone = models.CharField(max_length=9, blank=True, null=True)
    celular = models.CharField(max_length=10, blank=True, null=True)
    id_cliente = models.ForeignKey('DashboardEmpresas', models.DO_NOTHING, db_col='id_cliente', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dashboard_contatos'


class DashboardEmpresas(models.Model):
    id_cliente = models.SmallIntegerField(primary_key=True)
    nome_fantasia = models.CharField(db_col='nome fantasia', max_length=50, blank=True,
                                     null=True)  # Field renamed to remove unsuitable characters.
    nome_juridico = models.CharField(db_col='nome juridico', max_length=50, blank=True,
                                     null=True)  # Field renamed to remove unsuitable characters.
    cnpj = models.CharField(max_length=11)

    class Meta:
        managed = False
        db_table = 'dashboard_empresas'


class DashboardFuncionario(models.Model):
    id_func = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=100, blank=True, null=True)
    naturalidade_cid = models.CharField(max_length=20, blank=True, null=True)
    cor_raca = models.CharField(max_length=10, blank=True, null=True)
    data_nasc = models.DateField(blank=True, null=True)
    dependentes = models.IntegerField(blank=True, null=True)
    estado_civil = models.CharField(max_length=10, blank=True, null=True)
    mae = models.CharField(max_length=50, blank=True, null=True)
    nacionalidade = models.CharField(max_length=50, blank=True, null=True)
    naturalidade_estado = models.CharField(max_length=20, blank=True, null=True)
    pai = models.CharField(max_length=50, blank=True, null=True)
    sexo = models.CharField(max_length=10, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dashboard_funcionario'


class DashboardGestor(models.Model):
    gestor_id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=100)
    email = models.CharField(max_length=20, blank=True, null=True)
    celular = models.CharField(max_length=11, blank=True, null=True)
    especialidade = models.CharField(max_length=30, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dashboard_gestor'


class DashboardIndicadoresnegativos(models.Model):
    id = models.SmallIntegerField(primary_key=True)
    questao = models.SmallIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dashboard_indicadoresnegativos'


class DashboardLucratividade(models.Model):
    id = models.SmallIntegerField(primary_key=True)
    lucro_liquido_anual = models.SmallIntegerField(blank=True, null=True)
    receita_total_anual = models.SmallIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dashboard_lucratividade'


class DashboardPassivos(models.Model):
    id_passivo = models.SmallIntegerField(primary_key=True)
    nome = models.SmallIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dashboard_passivos'


class DashboardRoi(models.Model):
    id = models.SmallIntegerField(primary_key=True)
    receita = models.SmallIntegerField(blank=True, null=True)
    custo = models.SmallIntegerField(blank=True, null=True)
    item = models.SmallIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dashboard_roi'


class DashboardTaxaconversao(models.Model):
    visitantes = models.SmallIntegerField(primary_key=True)
    id = models.SmallIntegerField(blank=True, null=True)
    conversoes = models.SmallIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dashboard_taxaconversao'


class DashboardTicketmediovendas(models.Model):
    id = models.SmallIntegerField(primary_key=True)
    total_receita = models.SmallIntegerField(blank=True, null=True)
    total_vendas = models.SmallIntegerField(blank=True, null=True)
    nr_compras = models.SmallIntegerField(blank=True, null=True)
    periodo = models.DateField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dashboard_ticketmediovendas'


class DashboardTurnover(models.Model):
    id = models.SmallIntegerField(primary_key=True)
    contratados = models.SmallIntegerField(blank=True, null=True)
    desligamentos = models.SmallIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dashboard_turnover'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.SmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoChatterbotStatement(models.Model):
    text = models.CharField(max_length=255)
    created_at = models.DateTimeField()
    conversation = models.CharField(max_length=32)
    in_response_to = models.CharField(max_length=255, blank=True, null=True)
    persona = models.CharField(max_length=50)
    search_text = models.CharField(max_length=255)
    search_in_response_to = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'django_chatterbot_statement'

index/forms.py
from django import forms


class LandForm(forms.Form):


nome_empresa = forms.CharField(
    label='nome_empresa', max_length=50,)
nome_contato = forms.CharField(
    label='nome-contato', max_length=50)
celular = forms.CharField(
    label='celular', max_length=10)
email = forms.EmailField(
    label='email', max_length=254)

interesse = [
    ('Consultoria', 'Consultoria'),
    ('Treinamento', 'Treinamento'),
    ('Marketing', 'Marketing'),
    ('Outros', 'Outros'),
]

index/templates/index/land_form.back.html
{% extends "base.html" %} {% load static %} {% block content %}
<section class="hero is-medium">
    <div class="hero-body">
        <div class="container">
            <div class="col is-multiline is-centered cards-conytainer">
                <div class="col">
                    <div class="col">
                        <div class="col is-narrow">
                            <h1>
                                Você gostaria de transformar seu negócio com inteligência?
                            </h1>
                            <h1 class="subtitle">Ser estratégico é se preparar para enfrentar e vencer desafios,
                                enxergar ameaças e as oportunidades que ainda não existem. Ter uma visão a longo prazo
                                da organização deve ser o melhor caminho para alcançar a excelência. </h1>
                            <br>
                        </div>
                    </div>
                    <div class="col">
                        <div class="col is-narrow">
                            <figure class="image is-16by9">
                                <img src="/static/imgs/target.svg">
                            </figure>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="col is-multiline is-centered cards-conytainer" id="sectioncontainer">
                <div class="col">
                    <div class="col">
                        <div class="col is-narrow">
                            <div class="content">
                                <h1 class="title is-4">
                                    <p>Nós queremos ajudar o seu negócio. O mundo está digital, tudo está acontecendo a
                                        uma velocidade que não compreendemos ainda. Mas todo negócio continua sendo
                                        igual como seria um negócio na antiguidade. Oferta e demanda.Vendas.</p>
                                    <p>Porém antes de tornar seu negócio uma máquina de vendas, você precisa entender se
                                        o mesmo é sustentável. Se seus colaboradores entendem o seu motivo e o da sua
                                        empresa para estar no mercado.</p>
                                    <p>É nesse momento que entramos na sua vida, ajudando você através das informações
                                        que você já tem a encontrar uma estratégia vencedora, personalizada com suas
                                        necessidades e consistente com que o mercado precisa.</p>
                                    <p>É essa combinação de trabalho duro, foco e agilidade que compõe nossa
                                        consultoria.
                                    </p>
                                    <br>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="col is-narrow">
                            <div class="title">
                                Quero receber mais informações:
                            </div>
                            <form action="" enctype="multipart/form-data" method="post">
                                {% csrf_token %}
                                <div class="field">
                                    <label class="label" for="id_nome_empresa">Nome empresa:</label>
                                    <div class="control control has-icons-left has-icons-right">
                                        <input class="input" id="id_nome_empresa" maxlength="50" name="nome_empresa"
                                               placeholder="Nome da Empresa" type="text">
                                        <span class="icon is-small is-left">
                                            <i class="fas fa-building"></i>
                                        </span>
                                    </div>
                                </div>
                                <div class="field">
                                    <label class="label" for="id_nome_contato">Nome do Contato:</label>
                                    <div class="control control has-icons-left has-icons-right">
                                        <input class="input" id="id_nome_contato" maxlength="50" name="nome_contato"
                                               placeholder="Nome do Contato" type="text">
                                        <span class="icon is-small is-left">
                                            <i class="fas fa-user"></i>
                                        </span>
                                    </div>
                                </div>
                                <div class="field">
                                    <label class="label" for="id_celular">Contato:</label>
                                    <div class="control control has-icons-left has-icons-right">
                                        <input class="input" id="id_celular" maxlength="11" name="celular" placeholder="Contato"
                                               type="text">
                                        <span class="icon is-small is-left">
                                            <i class="fs fab fa-whatsapp fa-1x"></i>
                                        </span>
                                    </div>
                                </div>
                                <div class="field">
                                    <label class="label">Email</label>
                                    <div class="control has-icons-left
                                        has-icons-right">
                                        <input class="input" id="id_email" maxlength="254" name="email" placeholder="Email"
                                               type="email">
                                        <span class="icon is-small is-left">
                                            <i class="fas fa-envelope"></i>
                                        </span>
                                    </div>
                                </div>
                                <div class="field">
                                    <label class="label" for="id_interesse">Interesse:</label>
                                    <div class="control">
                                        <div class="select">
                                            <select id="id_interesse" name="interesse" required="">
                                                <option selected="" value="">---------</option>
                                                <option value="CS">Consultoria</option>
                                                <option value="TR">Treinamento</option>
                                                <option value="MK">Marketing</option>
                                                <option value="OU">Outros</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="field is-grouped">
                                    <div class="control">
                                        <input class="button is-success" type="submit" value="Enviar">
                                        <input class="button is-success" name="next" type="hidden" value="{{ next }}">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

index/templates/index/land_form.html
{% extends "base.html" %} {% load static %} {% block content %}

<header class="site-navbar js-sticky-header site-navbar-target" role="banner">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-6">
                <h1>
                    Você gostaria de transformar seu negócio com inteligência?
                </h1>
                <h5>O mundo está digital, tudo está acontecendo a uma velocidade impressionante, mas os negócios
                    continuam estruturados sobre o tripé: oferta, demanda e venda.
                    Porém, faz-se necessário entender o seu negócio. Saber se é sustentável. Estimular os
                    colaboradores
                    a compartilharem com os objetivos que levaram ao surgimento de sua empresa.
                    É nesse momento que a Business Data Consultoria entra em sua vida, ajudando sua empresa a
                    estruturar
                    as informações disponíveis, para que possam definir estratégias consistentes que fortaleçam a
                    presença de sua empresa no mercado.
                    Acreditamos que a combinação de trabalho, foco e agilidade, resultará no fortalecimento de sua
                    empresa.
                    Para nós, fazer parte dessa história será um prazer!
                    Entre em contato conosco
                </h5>
            </div>
            <div class="col-md-2">
                <img src="/static/imgs/target.svg" alt="Imagem de capa do card">
            </div>
        </div>
    </div>
</header>
<div class="site-section">
    <div class="container">
        <div class="row mb-5 align-items-end">
            <div class="col-md-6" data-aos="fade-up">
                <h2>Contato</h2>
                <p class="mb-0">Entre em contato conosco.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 ml-auto order-2" data-aos="fade-up">
                <ul class="list-unstyled">
                    <li class="mb-3">
                        <strong class="d-block mb-1">Address</strong>
                        <span>203 Fake St. Mountain View, San Francisco, California, USA</span>
                    </li>
                    <li class="mb-3">
                        <strong class="d-block mb-1">Phone</strong>
                        <span>+1 232 3235 324</span>
                    </li>
                    <li class="mb-3">
                        <strong class="d-block mb-1">Email</strong>
                        <span>youremail@domain.com</span>
                    </li>
                </ul>
            </div>
            <div class="col-md-6 mb-5 mb-md-0" data-aos="fade-up">
                <form action="" id="land_form" method="post" novalidate=""><input type="hidden"> {% csrf_token %}
                    <div class="row">
                        <div class="col-md-12 form-group">
                            <label for="id_nome_empresa">Nome da Empresa:</label>
                            <input class="form-control" id="id_nome_empresa" maxlength="50" name="nome_empresa"
                                type="text">
                            <div class="validate"></div>
                        </div>
                        <div class="col-md-12 form-group">
                            <label for="id_nome_contato">Nome do Contato:</label>
                            <input class="form-control" id="id_nome_contato" maxlength="50" name="nome_contato"
                                type="text">
                            <div class="validate"></div>
                        </div>
                        <div class="col-md-12 form-group">
                            <label for="id_celular">Celular:</label>
                            <input class="form-control" id="id_celular" maxlength="10" name="celular" type="text">
                        </div>
                        <div class="col-md-12 form-group">
                            <label for="id_email">Email:</label>
                            <input class="form-control" id="id_email" maxlength="254" name="email" type="email">
                            <div class="validate"></div>
                        </div>
                        <div class="col-md-12 form-group">
                            <label class="required" for="id_interesse">Interesse:</label>
                            <select class="form-control" id="id_interesse" name="interesse">
                                <option selected="" value="CS">Consultoria
                                </option>
                                <option value="TR">Treinamento</option>
                                <option value="MK">Marketing</option>
                                <option value="OU">Outros</option>
                            </select>
                        </div>
                        <div class="col-md-6 form-group">
                            <input class="button is-success" type="submit" value="Enviar">
                            <input class="button is-success" name="next" type="hidden" value="{{ next }}">
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>
<!-- <div class="site-section border-top border-bottom">
    <div class="container">
        <div class="row justify-content-center text-center mb-5">
            <div class="col-md-4">
                <h2 class="section-heading">Review From Our Users</h2>
            </div>
        </div>
        <div class="row justify-content-center text-center">
            <div class="col-md-7">
                <div class="owl-carousel testimonial-carousel">
                    <div class="review text-center">
                        <p class="stars">
                            <span class="icofont-star"></span>
                            <span class="icofont-star"></span>
                            <span class="icofont-star"></span>
                            <span class="icofont-star"></span>
                            <span class="icofont-star muted"></span>
                        </p>
                        <h3>Excellent App!</h3>
                        <blockquote>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius ea delectus pariatur,
                                numquam aperiam dolore nam optio dolorem facilis itaque voluptatum recusandae deleniti
                                minus animi, provident voluptates consectetur maiores
                                quos.
                            </p>
                        </blockquote>
                        <p class="review-user">
                            <img alt="Image" class="img-fluid rounded-circle mb-3" src="img/person_1.jpg">
                            <span class="d-block">
                                <span class="text-black">Jean Doe</span>, &mdash; App User
                            </span>
                        </p>
                    </div>
                    <div class="review text-center">
                        <p class="stars">
                            <span class="icofont-star"></span>
                            <span class="icofont-star"></span>
                            <span class="icofont-star"></span>
                            <span class="icofont-star"></span>
                            <span class="icofont-star muted"></span>
                        </p>
                        <h3>This App is easy to use!</h3>
                        <blockquote>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius ea delectus pariatur,
                                numquam aperiam dolore nam optio dolorem facilis itaque voluptatum recusandae deleniti
                                minus animi, provident voluptates consectetur maiores
                                quos.
                            </p>
                        </blockquote>
                        <p class="review-user">
                            <img alt="Image" class="img-fluid rounded-circle mb-3" src="img/person_2.jpg">
                            <span class="d-block">
                                <span class="text-black">Johan Smith</span>, &mdash; App User
                            </span>
                        </p>
                    </div>
                    <div class="review text-center">
                        <p class="stars">
                            <span class="icofont-star"></span>
                            <span class="icofont-star"></span>
                            <span class="icofont-star"></span>
                            <span class="icofont-star"></span>
                            <span class="icofont-star muted"></span>
                        </p>
                        <h3>Awesome functionality!</h3>
                        <blockquote>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius ea delectus pariatur,
                                numquam aperiam dolore nam optio dolorem facilis itaque voluptatum recusandae deleniti
                                minus animi, provident voluptates consectetur maiores
                                quos.
                            </p>
                        </blockquote>
                        <p class="review-user">
                            <img alt="Image" class="img-fluid rounded-circle mb-3" src="img/person_3.jpg">
                            <span class="d-block">
                                <span class="text-black">Jean Thunberg</span>, &mdash; App User
                            </span>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="site-section cta-section">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-6 mr-auto text-center text-md-left mb-5 mb-md-0">
                <h2>Starts Publishing Your Apps</h2>
            </div>
            <div class="col-md-5 text-center text-md-right">
                <p><a class="btn" href="#"><span class="icofont-brand-apple mr-3"></span>App store</a> <a class="btn"
                        href="#"><span class="icofont-ui-play mr-3"></span>Google play</a></p>
            </div>
        </div>
    </div>
</div> -->
</main>
</div>
<!-- .site-wrap -->
{% endblock %}