dashboard/urls.py
from django.urls import path
from . import views
from .views import ClienteDetail, ClienteCreate, ListClientes, ClienteUpdate, ClienteDelete
from .views import GestorCreate, FuncionarioCreate
from django.views.generic.base import TemplateView
from dashboard import grafs

urlpatterns = [
    path('', TemplateView.as_view(template_name='dashboard.html'), name='dashboard'),
    path('listclientes', ListClientes.as_view(), name='list'),
    path('cliente/<int:pk>/', ClienteDetail.as_view(), name='detail'),
    path('cadastro/', ClienteCreate.as_view(), name='new'),
    path('editar/<int:pk>/', ClienteUpdate.as_view(), name='update'),
    path('excluir/<int:pk>/', ClienteDelete.as_view(), name='delete'),
    path('gestor/', GestorCreate.as_view(), name='gestor'),
    path('funcionario/', FuncionarioCreate.as_view(), name='funcionario'),
]

index/urls.py
from django.urls import path
from index.views import Landing, IndexPageView
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', IndexPageView.as_view(), name='index'),
    path('land_form.html', Landing.as_view(), name='land'),
    path('descricao.html', TemplateView.as_view(
        template_name='descricao.html'), name='descricao'),
    path('empresa.html', TemplateView.as_view(
        template_name='empresa.html'), name='empresa'),
    path('servicos.html', TemplateView.as_view(
        template_name='servicos.html'), name='servicos'),
    path('clientes.html', TemplateView.as_view(
        template_name='clientes.html'), name='clientes'),
    path('blog.html', TemplateView.as_view(
        template_name='blog.html'), name='blog'),
]

projclinicas/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from dashboard.api.viewsets import FuncionarioViewset
from processos.api.viewsets import AtivosViewset, PassivosViewset

router = DefaultRouter()
# router.register(r'bdclientes', ClientesViewset, base_name='ClientesViewset')
router.register(r'funcionario', FuncionarioViewset,
                base_name='FuncionarioViewset')
router.register(r'ativos', AtivosViewset, base_name='AtivosViewset')
router.register(r'passivos', PassivosViewset, base_name='PassivosViewset')

urlpatterns = [
    path('', include('index.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
    path('chatbot/', include('chatbot.urls')),
    path('', include(router.urls)),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models


class Clientes(models.Model):

    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=30, blank=True, null=True)
    sobrenome = models.CharField(max_length=30, blank=True, null=True)
    cnpj = models.CharField(max_length=11, blank=False, null=True)
    celular = models.CharField(max_length=9, blank=True, null=True)
    email = models.CharField(max_length=254, blank=True, null=True)
    foto = models.ImageField(upload_to='fotos', null=True, blank=True)

    class Meta:
        ordering = ["nome"]

# Create your models here.


class Gestor(models.Model):
    gestor_id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=100)
    email = models.CharField(max_length=20, blank=True, null=True)
    celular = models.CharField(max_length=11, blank=True, null=True)
    especialidade = models.CharField(max_length=30, blank=True, null=True)


class Funcionario(models.Model):
    id_func = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=100, blank=True, null=True)
    nacionalidade = models.CharField(max_length=50, blank=True, null=True)
    naturalidade_cid = models.CharField(max_length=20, blank=True, null=True)
    naturalidade_estado = models.CharField(
        max_length=20, blank=True, null=True)
    data_nasc = models.DateField(blank=True, null=True)
    sexo = models.CharField(max_length=10, blank=True, null=True)
    estado_civil = models.CharField(max_length=10, blank=True, null=True)
    mae = models.CharField(max_length=50, blank=True, null=True)
    pai = models.CharField(max_length=50, blank=True, null=True)
    cor_raca = models.CharField(max_length=10, blank=True, null=True)
    dependentes = models.IntegerField(blank=True, null=True)


class Clinica(models.Model):
    clinica_id = models.AutoField(primary_key=True)
    nomefantasia = models.CharField(max_length=100)
    cnpj = models.CharField(unique=True, max_length=100)
    email = models.CharField(max_length=20, blank=True, null=True)
    contato = models.CharField(max_length=11, blank=True, null=True)
    especialidade = models.CharField(max_length=30, blank=True, null=True)


class Contatos(models.Model):
    nome = models.CharField(max_length=50, blank=True, null=True)
    sobrenome = models.CharField(max_length=50, blank=True, null=True)
    telefone = models.CharField(max_length=9, blank=True, null=True)
    celular = models.CharField(max_length=10, blank=True, null=True)

models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Ativos(models.Model):
    id_ativo = models.CharField(primary_key=True, max_length=-1)
    tipo_ativo = models.CharField(max_length=20, blank=True, null=True)
    descricao_passivo = models.CharField(max_length=20, blank=True, null=True)
    valor_ativo = models.IntegerField(blank=True, null=True)
    data_ativo = models.DateField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'ativos'


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.BooleanField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.BooleanField()
    is_active = models.BooleanField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class DashboardAtivos(models.Model):
    id_ativo = models.SmallIntegerField(blank=True, null=True)
    nome = models.SmallIntegerField(blank=True, null=True)
    valor = models.SmallIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dashboard_ativos'


class DashboardClientes(models.Model):
    nome = models.CharField(max_length=30, blank=True, null=True)
    sobrenome = models.CharField(max_length=30, blank=True, null=True)
    cnpj = models.CharField(max_length=11, blank=True, null=True)
    celular = models.CharField(max_length=9, blank=True, null=True)
    email = models.CharField(max_length=254, blank=True, null=True)
    foto = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dashboard_clientes'


class DashboardClinica(models.Model):
    clinica_id = models.AutoField(primary_key=True)
    nomefantasia = models.CharField(max_length=100)
    cnpj = models.CharField(unique=True, max_length=100)
    email = models.CharField(max_length=20, blank=True, null=True)
    contato = models.CharField(max_length=11, blank=True, null=True)
    especialidade = models.CharField(max_length=30, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dashboard_clinica'


class DashboardContatos(models.Model):
    nome = models.CharField(max_length=50, blank=True, null=True)
    sobrenome = models.CharField(max_length=50, blank=True, null=True)
    telefone = models.CharField(max_length=9, blank=True, null=True)
    celular = models.CharField(max_length=10, blank=True, null=True)
    id_cliente = models.ForeignKey('DashboardEmpresas', models.DO_NOTHING, db_col='id_cliente', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dashboard_contatos'


class DashboardEmpresas(models.Model):
    id_cliente = models.SmallIntegerField(primary_key=True)
    nome_fantasia = models.CharField(db_col='nome fantasia', max_length=50, blank=True,
                                     null=True)  # Field renamed to remove unsuitable characters.
    nome_juridico = models.CharField(db_col='nome juridico', max_length=50, blank=True,
                                     null=True)  # Field renamed to remove unsuitable characters.
    cnpj = models.CharField(max_length=11)

    class Meta:
        managed = False
        db_table = 'dashboard_empresas'


class DashboardFuncionario(models.Model):
    id_func = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=100, blank=True, null=True)
    naturalidade_cid = models.CharField(max_length=20, blank=True, null=True)
    cor_raca = models.CharField(max_length=10, blank=True, null=True)
    data_nasc = models.DateField(blank=True, null=True)
    dependentes = models.IntegerField(blank=True, null=True)
    estado_civil = models.CharField(max_length=10, blank=True, null=True)
    mae = models.CharField(max_length=50, blank=True, null=True)
    nacionalidade = models.CharField(max_length=50, blank=True, null=True)
    naturalidade_estado = models.CharField(max_length=20, blank=True, null=True)
    pai = models.CharField(max_length=50, blank=True, null=True)
    sexo = models.CharField(max_length=10, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dashboard_funcionario'


class DashboardGestor(models.Model):
    gestor_id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=100)
    email = models.CharField(max_length=20, blank=True, null=True)
    celular = models.CharField(max_length=11, blank=True, null=True)
    especialidade = models.CharField(max_length=30, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dashboard_gestor'


class DashboardIndicadoresnegativos(models.Model):
    id = models.SmallIntegerField(primary_key=True)
    questao = models.SmallIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dashboard_indicadoresnegativos'


class DashboardLucratividade(models.Model):
    id = models.SmallIntegerField(primary_key=True)
    lucro_liquido_anual = models.SmallIntegerField(blank=True, null=True)
    receita_total_anual = models.SmallIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dashboard_lucratividade'


class DashboardPassivos(models.Model):
    id_passivo = models.SmallIntegerField(primary_key=True)
    nome = models.SmallIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dashboard_passivos'


class DashboardRoi(models.Model):
    id = models.SmallIntegerField(primary_key=True)
    receita = models.SmallIntegerField(blank=True, null=True)
    custo = models.SmallIntegerField(blank=True, null=True)
    item = models.SmallIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dashboard_roi'


class DashboardTaxaconversao(models.Model):
    visitantes = models.SmallIntegerField(primary_key=True)
    id = models.SmallIntegerField(blank=True, null=True)
    conversoes = models.SmallIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dashboard_taxaconversao'


class DashboardTicketmediovendas(models.Model):
    id = models.SmallIntegerField(primary_key=True)
    total_receita = models.SmallIntegerField(blank=True, null=True)
    total_vendas = models.SmallIntegerField(blank=True, null=True)
    nr_compras = models.SmallIntegerField(blank=True, null=True)
    periodo = models.DateField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dashboard_ticketmediovendas'


class DashboardTurnover(models.Model):
    id = models.SmallIntegerField(primary_key=True)
    contratados = models.SmallIntegerField(blank=True, null=True)
    desligamentos = models.SmallIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dashboard_turnover'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.SmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoChatterbotStatement(models.Model):
    text = models.CharField(max_length=255)
    created_at = models.DateTimeField()
    conversation = models.CharField(max_length=32)
    in_response_to = models.CharField(max_length=255, blank=True, null=True)
    persona = models.CharField(max_length=50)
    search_text = models.CharField(max_length=255)
    search_in_response_to = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'django_chatterbot_statement'

dashboard/forms.py
from django import forms


class ClienteForms(forms.Form):

    nome = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'special'}))
    sobrenome = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'special'}))
    cnpj = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'special'}))
    celular = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'special'}))
    email = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'special'}))


class FuncionarioForms(forms.Form):

    nome = forms.CharField(max_length=100, widget=forms.TextInput)
    nacionalidade = forms.CharField(max_length=50, widget=forms.TextInput)
    naturalidade_cid = forms.CharField(
        max_length=20, widget=forms.TextInput)
    naturalidade_estado = forms.CharField(
        max_length=20, widget=forms.TextInput)
    data_nasc = forms.DateField(widget=forms.DateField)
    sexo = forms.CharField(max_length=8, widget=forms.TextInput)
    estado_civil = forms.CharField(max_length=5, widget=forms.TextInput)
    mae = forms.CharField(max_length=50, widget=forms.TextInput)
    pai = forms.CharField(max_length=50, widget=forms.TextInput)
    cor_raca = forms.CharField(max_length=10, widget=forms.TextInput)
    dependentes = forms.IntegerField(widget=forms.TextInput)

processos/forms.py
from django import forms


class AtivosForm(forms.Form):
    tipo_ativo = forms.CharField(label='Tipo Ativo', max_length=20)
    descricao_ativo = forms.CharField(label='Descrição Ativo', max_length=20)
    valor_ativo = forms.IntegerField(label='Valor do Ativo')
    data_ativo = forms.DateField(label='Data do Ativo')


class RentForm(forms.Form):
    mes = [
        ('JAN', 'Janeiro'),
        ('FEV', 'Fevereiro'),
        ('MAR', 'Março'),
        ('ABR', 'Abril'),
        ('MAI', 'Maio'),
        ('JUN', 'Junho'),
        ('JUL', 'Julho'),
        ('AGO', 'Agosto'),
        ('SET', 'Setembro'),
        ('OUT', 'Outubro'),
        ('NOV', 'Novembro'),
        ('DEZ', 'Dezembro'),
    ]
    investimento = forms.CharField(label='investimento', max_length=20)
    lucro_liquido = forms.CharField(label='lucro', max_length=20)


]

dashboard/templates/dashboard/ativos_form.html
{% extends "base.html" %} {% load static %} {% block content %}

<header class="jumbotron is-light">
    <div class="hero-head">
    </div>
</header>

<div>
    <div class="col">
        {% include 'nav.html' %}
        <main class="col">
            <div class="level">
                <div class="level-left">
                    <div class="level-item">
                        <div class="title">Painel de Gestão do {{ user.username }}</div>
                    </div>
                </div>
                <div class="level-right">
                    <div class="level-item">
                        <button type="button" class="button is-small">
                            Hoje é {% now " D j F Y H:i" %}
            </button>
                    </div>
                </div>
            </div>
            <h1 class="title is-2">Clientes</h1>
            <!--            <form action="/dashboard/" method="post">-->
            <!--                {% csrf_token %}-->
            <!--                {{ form.as_p }}-->
            <!--                <input type="submit" value="Submit">-->
            <!--            </form>-->
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <p><label class="label" for="id_tipo_ativo">Tipo ativo:</label>
                    <input class="input" type="text" name="tipo_ativo" maxlength="20" id="id_tipo_ativo"></p>
                <p><label class="label" for="id_descricao_ativo">Descricao ativo:</label>
                    <input class="input" type="text" name="descricao_ativo" maxlength="20" id="id_descricao_ativo"></p>
                <p><label class="label" for="id_valor_ativo">Valor ativo:</label>
                    <input class="input" type="number" name="valor_ativo" id="id_valor_ativo"></p>
                <p><label class="label" for="id_data_ativo">Data ativo:</label>
                    <input class="input" type="text" name="data_ativo" id="id_data_ativo"></p>
                <br>
                <button class="button is-success" type="submit" value="Salvar">Salvar</button>
            </form>

        </main>
    </div>
</div>
{% endblock%}

dashboard/templates/dashboard/clientes_confirm_delete.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<header class="hero is-light">
  <div class="hero-head">
  </div>
</header>

<div>
    <div class="col">
        {% include 'nav.html' %}
        <main class="col">
            <div class="level">
                <div class="level-left">
                    <div class="level-item">
                        <div class="title">Painel de Gestão do {{ user.username }}</div>
                    </div>
                </div>
                <div class="level-right">
                    <div class="level-item">
                        <button class="button is-small" type="button">
                            Hoje é {% now " D j F Y H:i" %}
            </button>
          </div>
        </div>
      </div>
      <h1 class="title is-2">Clientes</h1>
      <form method="post">{% csrf_token %}
        <p>Tem certeza que deseja deletar o cliente "{{ object.nome }}"?</p>
        <button class="button is-danger" type="submit" value="Confirm">Confirmar</button>
      </form>
    </main>
  </div>
</div>
{% endblock %}

dashboard/templates/dashboard/clientes_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<header class="jumbotron is-light">
    <div class="jumbotron-head">
    </div>
</header>

<div>
    <div class="col">
        {% include 'nav.html' %}
        <main class="col">
            {% include 'breadcumbs.html' %}
            <div class="level">
                <div class="level-left">
                    <div class="level-item">
                        <div class="title">Painel de Gestão do {{ user.username }}</div>
                    </div>
                </div>
                <div class="level-right">
                    <div class="level-item">
                        <button type="button" class="button is-small">
                            Hoje é {% now " D j F Y H:i" %}
                        </button>
                    </div>
                </div>
            </div>
              <h1 class="title is-1">Informações do Cliente</h1>
                    <table class="table">
                      <thead>
                        <tr>
                          <th>Nome</th>
                          <th>SobreNome</th>
                          <th>Cnpj</th>
                          <th>Celular</th>
                          <th>Email</th>
                          <th>Atualizar</th>
                          <th>Excluir</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <th>{{ object.nome }}</th>
                          <td>{{ object.sobrenome }}</td>
                          <td>{{ object.cnpj }}</td>
                          <td>{{ object.celular }}</td>
                          <td>{{ object.email }}</td>
                          <td><a  href="{% url 'update' object.pk %}"><span class="button is-success">Atualizar</span></a></td>
                          <td><a  href="{% url 'delete' object.pk %}"><span class="button is-danger">Excluir</span></a></td>
                      </tbody>
                    </table>
                </div>
        </main>
    </div>
</div>
{% endblock%}

dashboard/templates/dashboard/clientes_update.html
{% extends "base.html" %}
{% block content %}
<section class="hero">
    <div class="hero-body">
        <div class="container has-text-centered">
            <div class="col is-4 is-offset-4">
                <div id="content" class="colM">
                    <h1 class="title is-2">Clientes</h1>
                    <form method="post">{% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="Update">
                    </form>
                    <br>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock%}

dashboard/templates/dashboard/funcionario_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div>
    <div class="col">
        {% include 'nav.html' %}
        <main class="col">
            {% include 'breadcumbs.html' %}
            <div class="level">
                <div class="level-left">
                    <div class="level-item">
                        <div class="title">Painel de Gestão do {{ user.username }}</div>
                    </div>
                </div>
                <div class="level-right">
                    <div class="level-item">
                        <button type="button" class="button is-small">
                            Hoje é {% now " D j F Y H:i" %}
                        </button>
                    </div>
                </div>
            </div>
            <div class="col is-two-thirds">
                <form action="" method="post">
                    {% csrf_token %}

                    <div id="div_id_nome" class="field">
                        <label for="" class="label">Nome Completo</label>
                        <input type="text" name="nome" maxlength="100" class="input" id="id_nome">
                    </div>

                    <div id="div_id_nacionalidade" class="field">
                        <label for="" class="label">Nacionalidade</label>
                        <input type="text" name="nacionalidade" maxlength="50" class="input" id="id_nacionalidade">
                    </div>

                    <div id="div_id_naturalidade_cid" class="field">
                        <label for="" class="label">Naturalidade Cidade</label>
                        <input type="text" name="naturalidade_cid" maxlength="20" class="input" id="id_naturalidade_cid">
                    </div>

                    <div id="div_id_naturalidade_estado" class="field">
                        <label for="" class="label">Naturalidade Estado</label>
                        <input type="text" name="naturalidade_estado" maxlength="20" class="input" id="id_naturalidade_estado">
                    </div>

                    <div id="div_id_data_nasc" class="field">
                        <label for="" class="label">Data de Nascimento</label>
                        <input type="date" name="data_nasc" class="input" id="id_data_nasc">
                    </div>

                    <div id="div_id_sexo" class="field">
                        <label for="" class="label">Sexo</label>
                        <input type="text" name="sexo" maxlength="10" class="input" id="id_sexo">
                    </div>

                    <div id="div_id_estado_civil" class="field">
                        <label for="" class="label">Estado civil</label>
                        <input type="text" name="estado_civil" maxlength="10" class="input" id="id_estado_civil">
                    </div>

                    <div id="div_id_mae" class="field"><label for="" class="label">Mãe</label>
                        <input type="text" name="mae" maxlength="50" class="input" id="id_mae">
                    </div>
                    <div id="div_id_pai" class="field"><label for="" class="label">Pai</label>
                        <input type="text" name="pai" maxlength="50" class="input" id="id_pai">
                    </div>
                    <div id="div_id_cor_raca" class="field">
                        <label for="" class="label">Cor raca</label>
                        <input type="text" name="cor_raca" maxlength="10" class="input" id="id_cor_raca">
                    </div>
                    <div id="div_id_dependentes" class="field">
                        <label for="" class="label">Dependentes</label>
                        <input type="text" name="dependentes" class="input" id="id_dependentes">
                    </div>
                    <button class="button is-success" type="submit" value="Salvar">Salvar</button>
                </form>
            </div>
        </main>
    </div>
</div>

{% endblock%}

dashboard/templates/dashboard/rentabilidade_form.html
{% load static %} {% block content %} {% load l10n %} {% load plotly_dash %}

<!DOCTYPE html>
<html lang="pt_br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge"> {% block title %}
    <title>Business Data Consultoria LTDA - Negócios Inteligentes</title>{% endblock %}
    <link rel="stylesheet" href="/static/styles/bulma/css/main.css">
</head>

<body>
<div class="hero-head">
    {% include "menu_dash.html" %}
</div>
<div class="col">
    <div class="col is-3 ">
        {% include 'nav.html' %}
    </div>
    <div class="col is-5">
        <h1 class="title is-2">RENTABILIDADE</h1>
        <form action="" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            <div class="field">
                <label class="label" for="id_data_inicio">Data Inicial:</label>
                <div class="control control has-icons-left has-icons-right">
                    <input class="input" class="vDateField" id="id_data_inicio" name="data_inicio" size="10"
                           type="date">
                </div>
            </div>
            <div class="field">
                    <label class="label" for="id_data_fim">Data Inicial:</label>
                    <div class="control control has-icons-left has-icons-right">
                        <input class="input" type="date" name="data_fim" class="vDateField" size="10" id="id_data_fim">
                    </div>
                </div>
                <div class="field">
                    <label class="label" for="id_investimento">Investimento:</label>
                    <div class="control control has-icons-left has-icons-right">
                        <input class="input" type="number" name="investimento" step="0.01" required="" id="id_investimento">
                        <span class="icon is-small is-left">
                            <i class="fas fa-building"></i>
                        </span>
                    </div>
                </div>
                <div class="field">
                    <label class="label" for="id_lucro_liquido">Lucro Liquido:</label>
                    <div class="control control has-icons-left has-icons-right">
                      <input class="input" type="number" name="lucro_liquido" step="0.01" required="" id="id_lucro_liquido">
                        <span class="icon is-small is-left">
                            <i class="fas fa-user"></i>
                        </span>
                    </div>
                </div>
                <div class="field">
                    <label class="label" for="id_rentabilidade">Rentabilidade:</label>
                    <div class="control control has-icons-left has-icons-right">
                        <input class="input" type="number" name="rentabilidade" step="0.01" required="" id="id_rentabilidade">
                        <span class="icon is-small is-left">
                            <i class="fas fa-user"></i>
                        </span>
                    </div>
                </div>
                <div class="field is-grouped">
                    <div class="control">
                        <input class="button is-success" type="submit" value="Enviar">
                        <input class="button is-success" type="hidden" name="next" value="{{ next }}">
                    </div>
                </div>
            </form>
        </div>
    </div>
</body>
</html>

{% endblock %}